### ISSUE TITLE
Could not add service massages to rosmsg_include

### ISSUE THREAD

**Issue by strdn** [adnanademovic/rosrust#107]
Appears on recent `rosrust` revisions, but works fine with `rosrust 0.7.1`
```console
error[E0404]: expected trait, found struct `rosrust::Service`
  --> chain-rpc-ros/src/msg.rs:21:1
   | use rosrust_codegen::rosmsg_include;
   |
21 | / rosmsg_include!(
22 | |     std_srvs / Empty,
23 | | );
   | |__^ not a trait
```

**Comment by adnanademovic** [comment]
I could not replicate the issue.
If you could create an isolated example that fails, that would be great!

**Comment by strdn** [comment]
@adnanademovic,
perhaps the error was due to the direct dependency inclusion rosrust_codegen to my Cargo.toml
Now I have updated dependencies 0.8.0 and all works fine.
